#!/usr/bin/env python3
"""
Regenerate app/utils/fh6-cars.ts with the full FH6 CarOrdinal -> name map.

The telemetry stream only carries the numeric CarOrdinal; the names live in a
community list extracted from the game files. This script downloads that list
and writes the lookup table the app uses, so every car auto-names instead of
showing "Car #1513".

Run it on a normal machine (this needs plain internet access), from the repo
root:

    python scripts/fetch_fh6_cars.py

...or with your explicit interpreter, e.g. on Windows:

    & "C:\\Users\\<you>\\AppData\\Local\\Python\\pythoncore-3.14-64\\python.exe" scripts/fetch_fh6_cars.py

Then rebuild:  docker compose up --build

Re-run after game updates to pick up new cars. Source (community-maintained):
https://gist.github.com/HDR/0659d1717bc61504bf83750628963f4f
"""

import json
import os
import sys
import urllib.request

GIST_RAW = "https://gist.githubusercontent.com/HDR/0659d1717bc61504bf83750628963f4f/raw/"
OUT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "app", "utils", "fh6-cars.ts"))

# Keep these even if the source omits them (verified from telemetry).
PINNED = {1513: "Maserati Ghibli Cup"}


def build_ts(entries):
    body = ",\n".join(f"  {n}: {json.dumps(name, ensure_ascii=False)}" for n, name in entries)
    return f"""/**
 * FH6 car library — CarOrdinal → name. AUTO-GENERATED by
 * scripts/fetch_fh6_cars.py from the community FH6 ordinal list
 * (https://gist.github.com/HDR/0659d1717bc61504bf83750628963f4f).
 * {len(entries)} cars. Re-run the script to refresh; do not edit by hand
 * (a display name set in co-driver's garage overrides this anyway).
 */

export const FH6_CAR_NAMES: Record<number, string> = {{
{body}
}}

/** Name for an ordinal, or null when it isn't in the library. */
export function fh6CarName(ordinal: number | null | undefined): string | null {{
  if (ordinal == null) return null
  return FH6_CAR_NAMES[ordinal] ?? null
}}
"""


def main():
    print(f"Downloading FH6 car list from:\n  {GIST_RAW}")
    try:
        with urllib.request.urlopen(GIST_RAW, timeout=30) as resp:
            raw = json.loads(resp.read().decode("utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: could not download/parse the list: {e}", file=sys.stderr)
        print("Check your internet connection and try again.", file=sys.stderr)
        sys.exit(1)

    # Source maps "car name" -> "ordinal" (string). Invert to ordinal -> name.
    by_ordinal = dict(PINNED)
    added = 0
    for name, ordinal in raw.items():
        try:
            n = int(ordinal)
        except (TypeError, ValueError):
            continue
        if n not in by_ordinal:          # pinned + first-seen wins
            by_ordinal[n] = name.strip()
            added += 1

    entries = sorted(by_ordinal.items())
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(build_ts(entries))

    print(f"Wrote {len(entries)} cars → {OUT}")
    print("Now rebuild:  docker compose up --build")


if __name__ == "__main__":
    main()
